/**
 * This file is autogenerated by ShadowBid mock script.
 * Deployment failed due to devnet incompatibility, so we mock the address.
 */

const deployedContracts = {
  devnet: {
    ShadowBid: {
      address: "0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d",
      abi: [
  {
    "type": "impl",
    "name": "ShadowBidImpl",
    "interface_name": "contracts::shadow_bid::IShadowBid"
  },
  {
    "type": "struct",
    "name": "core::integer::u256",
    "members": [
      {
        "name": "low",
        "type": "core::integer::u128"
      },
      {
        "name": "high",
        "type": "core::integer::u128"
      }
    ]
  },
  {
    "type": "struct",
    "name": "core::array::Span::<core::felt252>",
    "members": [
      {
        "name": "snapshot",
        "type": "@core::array::Array::<core::felt252>"
      }
    ]
  },
  {
    "type": "enum",
    "name": "contracts::shadow_bid::AuctionState",
    "variants": [
      {
        "name": "Open",
        "type": "()"
      },
      {
        "name": "Revealing",
        "type": "()"
      },
      {
        "name": "Settled",
        "type": "()"
      },
      {
        "name": "Cancelled",
        "type": "()"
      }
    ]
  },
  {
    "type": "struct",
    "name": "contracts::shadow_bid::AuctionInfo",
    "members": [
      {
        "name": "seller",
        "type": "core::starknet::contract_address::ContractAddress"
      },
      {
        "name": "item_hash",
        "type": "core::felt252"
      },
      {
        "name": "min_price",
        "type": "core::integer::u256"
      },
      {
        "name": "bid_deadline",
        "type": "core::integer::u64"
      },
      {
        "name": "reveal_deadline",
        "type": "core::integer::u64"
      },
      {
        "name": "state",
        "type": "contracts::shadow_bid::AuctionState"
      },
      {
        "name": "bid_count",
        "type": "core::integer::u32"
      },
      {
        "name": "highest_bid",
        "type": "core::integer::u256"
      },
      {
        "name": "winner",
        "type": "core::starknet::contract_address::ContractAddress"
      }
    ]
  },
  {
    "type": "enum",
    "name": "core::bool",
    "variants": [
      {
        "name": "False",
        "type": "()"
      },
      {
        "name": "True",
        "type": "()"
      }
    ]
  },
  {
    "type": "interface",
    "name": "contracts::shadow_bid::IShadowBid",
    "items": [
      {
        "type": "function",
        "name": "create_auction",
        "inputs": [
          {
            "name": "item_hash",
            "type": "core::felt252"
          },
          {
            "name": "min_price",
            "type": "core::integer::u256"
          },
          {
            "name": "bid_duration",
            "type": "core::integer::u64"
          },
          {
            "name": "reveal_duration",
            "type": "core::integer::u64"
          }
        ],
        "outputs": [
          {
            "type": "core::integer::u256"
          }
        ],
        "state_mutability": "external"
      },
      {
        "type": "function",
        "name": "submit_bid",
        "inputs": [
          {
            "name": "auction_id",
            "type": "core::integer::u256"
          },
          {
            "name": "bid_commitment",
            "type": "core::felt252"
          },
          {
            "name": "deposit",
            "type": "core::integer::u256"
          },
          {
            "name": "proof",
            "type": "core::array::Span::<core::felt252>"
          }
        ],
        "outputs": [],
        "state_mutability": "external"
      },
      {
        "type": "function",
        "name": "reveal_bid",
        "inputs": [
          {
            "name": "auction_id",
            "type": "core::integer::u256"
          },
          {
            "name": "bid_amount",
            "type": "core::integer::u256"
          },
          {
            "name": "salt",
            "type": "core::felt252"
          }
        ],
        "outputs": [],
        "state_mutability": "external"
      },
      {
        "type": "function",
        "name": "settle_auction",
        "inputs": [
          {
            "name": "auction_id",
            "type": "core::integer::u256"
          }
        ],
        "outputs": [],
        "state_mutability": "external"
      },
      {
        "type": "function",
        "name": "withdraw_refund",
        "inputs": [
          {
            "name": "auction_id",
            "type": "core::integer::u256"
          }
        ],
        "outputs": [],
        "state_mutability": "external"
      },
      {
        "type": "function",
        "name": "claim_seller_payment",
        "inputs": [
          {
            "name": "auction_id",
            "type": "core::integer::u256"
          }
        ],
        "outputs": [],
        "state_mutability": "external"
      },
      {
        "type": "function",
        "name": "get_auction",
        "inputs": [
          {
            "name": "auction_id",
            "type": "core::integer::u256"
          }
        ],
        "outputs": [
          {
            "type": "contracts::shadow_bid::AuctionInfo"
          }
        ],
        "state_mutability": "view"
      },
      {
        "type": "function",
        "name": "get_auction_count",
        "inputs": [],
        "outputs": [
          {
            "type": "core::integer::u256"
          }
        ],
        "state_mutability": "view"
      },
      {
        "type": "function",
        "name": "has_bid",
        "inputs": [
          {
            "name": "auction_id",
            "type": "core::integer::u256"
          },
          {
            "name": "bidder",
            "type": "core::starknet::contract_address::ContractAddress"
          }
        ],
        "outputs": [
          {
            "type": "core::bool"
          }
        ],
        "state_mutability": "view"
      },
      {
        "type": "function",
        "name": "has_revealed",
        "inputs": [
          {
            "name": "auction_id",
            "type": "core::integer::u256"
          },
          {
            "name": "bidder",
            "type": "core::starknet::contract_address::ContractAddress"
          }
        ],
        "outputs": [
          {
            "type": "core::bool"
          }
        ],
        "state_mutability": "view"
      }
    ]
  },
  {
    "type": "constructor",
    "name": "constructor",
    "inputs": [
      {
        "name": "verifier_address",
        "type": "core::starknet::contract_address::ContractAddress"
      },
      {
        "name": "payment_token",
        "type": "core::starknet::contract_address::ContractAddress"
      }
    ]
  },
  {
    "type": "event",
    "name": "contracts::shadow_bid::ShadowBid::AuctionCreated",
    "kind": "struct",
    "members": [
      {
        "name": "auction_id",
        "type": "core::integer::u256",
        "kind": "key"
      },
      {
        "name": "seller",
        "type": "core::starknet::contract_address::ContractAddress",
        "kind": "key"
      },
      {
        "name": "item_hash",
        "type": "core::felt252",
        "kind": "data"
      },
      {
        "name": "min_price",
        "type": "core::integer::u256",
        "kind": "data"
      },
      {
        "name": "bid_deadline",
        "type": "core::integer::u64",
        "kind": "data"
      },
      {
        "name": "reveal_deadline",
        "type": "core::integer::u64",
        "kind": "data"
      }
    ]
  },
  {
    "type": "event",
    "name": "contracts::shadow_bid::ShadowBid::BidSubmitted",
    "kind": "struct",
    "members": [
      {
        "name": "auction_id",
        "type": "core::integer::u256",
        "kind": "key"
      },
      {
        "name": "bidder",
        "type": "core::starknet::contract_address::ContractAddress",
        "kind": "key"
      }
    ]
  },
  {
    "type": "event",
    "name": "contracts::shadow_bid::ShadowBid::BidRevealed",
    "kind": "struct",
    "members": [
      {
        "name": "auction_id",
        "type": "core::integer::u256",
        "kind": "key"
      },
      {
        "name": "bidder",
        "type": "core::starknet::contract_address::ContractAddress",
        "kind": "key"
      },
      {
        "name": "amount",
        "type": "core::integer::u256",
        "kind": "data"
      }
    ]
  },
  {
    "type": "event",
    "name": "contracts::shadow_bid::ShadowBid::AuctionSettled",
    "kind": "struct",
    "members": [
      {
        "name": "auction_id",
        "type": "core::integer::u256",
        "kind": "key"
      },
      {
        "name": "winner",
        "type": "core::starknet::contract_address::ContractAddress",
        "kind": "data"
      },
      {
        "name": "winning_bid",
        "type": "core::integer::u256",
        "kind": "data"
      }
    ]
  },
  {
    "type": "event",
    "name": "contracts::shadow_bid::ShadowBid::RefundClaimed",
    "kind": "struct",
    "members": [
      {
        "name": "auction_id",
        "type": "core::integer::u256",
        "kind": "key"
      },
      {
        "name": "bidder",
        "type": "core::starknet::contract_address::ContractAddress",
        "kind": "key"
      },
      {
        "name": "amount",
        "type": "core::integer::u256",
        "kind": "data"
      }
    ]
  },
  {
    "type": "event",
    "name": "contracts::shadow_bid::ShadowBid::SellerPaymentClaimed",
    "kind": "struct",
    "members": [
      {
        "name": "auction_id",
        "type": "core::integer::u256",
        "kind": "key"
      },
      {
        "name": "seller",
        "type": "core::starknet::contract_address::ContractAddress",
        "kind": "key"
      },
      {
        "name": "amount",
        "type": "core::integer::u256",
        "kind": "data"
      }
    ]
  },
  {
    "type": "event",
    "name": "contracts::shadow_bid::ShadowBid::Event",
    "kind": "enum",
    "variants": [
      {
        "name": "AuctionCreated",
        "type": "contracts::shadow_bid::ShadowBid::AuctionCreated",
        "kind": "nested"
      },
      {
        "name": "BidSubmitted",
        "type": "contracts::shadow_bid::ShadowBid::BidSubmitted",
        "kind": "nested"
      },
      {
        "name": "BidRevealed",
        "type": "contracts::shadow_bid::ShadowBid::BidRevealed",
        "kind": "nested"
      },
      {
        "name": "AuctionSettled",
        "type": "contracts::shadow_bid::ShadowBid::AuctionSettled",
        "kind": "nested"
      },
      {
        "name": "RefundClaimed",
        "type": "contracts::shadow_bid::ShadowBid::RefundClaimed",
        "kind": "nested"
      },
      {
        "name": "SellerPaymentClaimed",
        "type": "contracts::shadow_bid::ShadowBid::SellerPaymentClaimed",
        "kind": "nested"
      }
    ]
  }
],
      classHash: "0xMockClassHash" 
    }
  }
} as const;

export default deployedContracts;
