const fs = require('fs');
const path = require('path');

const artifactPath = '/Users/mustang/Desktop/shadow-bid/packages/snfoundry/contracts/target/dev/contracts_ShadowBid.contract_class.json';
const outputPath = '/Users/mustang/Desktop/shadow-bid/packages/nextjs/contracts/deployedContracts.ts';

try {
    if (!fs.existsSync(artifactPath)) {
        console.error(`Artifact not found at ${artifactPath}`);
        process.exit(1);
    }

    const fileContent = fs.readFileSync(artifactPath, 'utf8');
    const artifact = JSON.parse(fileContent);

    // The ABI in the sierra artifact is a stringified JSON
    let abi;
    if (typeof artifact.abi === 'string') {
        abi = JSON.parse(artifact.abi);
    } else {
        abi = artifact.abi;
    }

    const content = `/**
 * This file is autogenerated by ShadowBid mock script.
 * Deployment failed due to devnet incompatibility, so we mock the address.
 */

const deployedContracts = {
  devnet: {
    ShadowBid: {
      address: "0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d",
      abi: ${JSON.stringify(abi, null, 2)},
      classHash: "${artifact.sierra_program ? '0xMockClassHash' : '0x0'}" 
    }
  }
} as const;

export default deployedContracts;
`;

    const outputDir = path.dirname(outputPath);
    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }

    fs.writeFileSync(outputPath, content);
    console.log('Mock deployedContracts.ts generated successfully.');

} catch (error) {
    console.error('Error generating mock contracts:', error);
    process.exit(1);
}
